logging:
  level:
    io.pivotal: ERROR
